remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one



tittle: BIENVENIDO CIPRIANO MOICHE WILLIAMS

name: ESTO ES 2 ASIR DE INFORMÁTICA